name: Deploy to VDS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            /.next/cache
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('/package-lock.json') }}-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('/package-lock.json') }}-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-tales:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: VDS deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USERNAME }}
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ai-tales:latest
            docker stop ai-tales || true
            docker rm ai-tales || true
            docker run -d --restart always --name ai-tales -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/ai-tales:latest